nacos:
    dir:
      log: /tmp/nacos/log
      cache: /tmp/nacos/cache
    logLevel: debug
    username: nacos
    password: nacos
    timeoutMs: 5000
    notLoadCacheAtStart: true
    ip: 127.0.0.1
    port: 8848
    contextPath: /nacos